# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10e288b36ba3e3972a1285497a079034b2cf27c4c505e85e346a2df233cb2eda07cae77dd9351c9775e64ee8c93b1f8225f2222448796c8d694fd658f32fd681

test:
  secret_key_base: a7972530fbf1853ccda51883393bf725d7ab1cba258c2c7a362d9da2ae71dd3b8443b2c41798afe4e58c8b1bcacf7d395c4e882361528e01fc1c5d6ea692be02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
